### ISSUE TITLE
Editing cells is not working well. 

### ISSUE THREAD

**Issue by soerendip** [preftech/dash-tabulator#25]
Sometimes I have to click 4 times to end up in the cell to edit the cell. Sometimes, when the cursor appears the cell gets deactivated for no obvious reason and has to be selected again. Is that normal or is there rather something wrong with my setup?

I use `'editor'='input'` in the column definition.

**Comment by pjaol** [comment]
Have you registered any other callbacks? 
If you look at 
https://github.com/preftech/dash-tabulator/blob/2e7ff92d4446c79a05e6dd71d01593a1aa0eafc6/src/lib/components/DashTabulator.react.js#L68

In order to make cellEdit work I have to disable rendering using 
```js
this.shouldRerender = false; 
```
Otherwise render() will redraw the object on the screen and interrupt the editor interface.

**Comment by pjaol** [comment]
Just noticed #26 this might be caused by having an older version of dash-tabulator
Try upgrading first
```
pip install dash-tabulator -U
```

**Comment by soerendip** [comment]
Ok, works much better!!
